/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PopUpStart.java
 *
 * Created on 28 mai 2009, 14:56:41
 */

package pithreads.visualisation;

import pithreads.framework.debug.Receiver;
import pithreads.visualisation.model.IModel;
import pithreads.visualisation.model.Model;

/**
 *
 * @author mathurin
 */
public class PopUpStart extends javax.swing.JFrame {
    private IModel model;
    private ApplicationController controller;

    /** Creates new form PopUpStart */
    public PopUpStart(Receiver eventList) {
        initComponents();
        this.model = new Model();
        this.controller = new ApplicationController(eventList,model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        writeInFileExeCheckBoxYes = new javax.swing.JCheckBox();
        writeInFileExeCheckBoxNo = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        speedGeneralTextBox = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        speedMovementsTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        speedOrganizationTextBox = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Propriétés de l'application");
        setAlwaysOnTop(true);
        setResizable(false);

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        okButton.setText("Ok");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Voulez-vous enregistrer l'execution dans un fichier :");

        writeInFileExeCheckBoxYes.setSelected(true);
        writeInFileExeCheckBoxYes.setText("oui");
        writeInFileExeCheckBoxYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeInFileExeCheckBoxYesActionPerformed(evt);
            }
        });

        writeInFileExeCheckBoxNo.setText("non");
        writeInFileExeCheckBoxNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                writeInFileExeCheckBoxNoActionPerformed(evt);
            }
        });

        jLabel3.setText("Durée de chaque \"états\" :");

        speedGeneralTextBox.setText("600");

        jLabel4.setText("Durée des mouvements :");

        speedMovementsTextBox.setText("10000");

        jLabel5.setText("Durée des réorganisations : ");

        speedOrganizationTextBox.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(okButton))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(speedOrganizationTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(speedMovementsTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                                    .addComponent(speedGeneralTextBox, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(writeInFileExeCheckBoxYes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(writeInFileExeCheckBoxNo)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(writeInFileExeCheckBoxYes)
                    .addComponent(writeInFileExeCheckBoxNo)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(speedGeneralTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(speedMovementsTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(speedOrganizationTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
}//GEN-LAST:event_cancelButtonActionPerformed

    private void writeInFileExeCheckBoxYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeInFileExeCheckBoxYesActionPerformed
        if(! writeInFileExeCheckBoxYes.isSelected()){
        writeInFileExeCheckBoxYes.setSelected(true);
        }
        writeInFileExeCheckBoxNo.setSelected(false);
    }//GEN-LAST:event_writeInFileExeCheckBoxYesActionPerformed

    private void writeInFileExeCheckBoxNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_writeInFileExeCheckBoxNoActionPerformed
        if(! writeInFileExeCheckBoxNo.isSelected()){
        writeInFileExeCheckBoxNo.setSelected(true);
        }
        writeInFileExeCheckBoxYes.setSelected(false);
    }//GEN-LAST:event_writeInFileExeCheckBoxNoActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       model.setMilliSpeed(Integer.parseInt(this.speedGeneralTextBox.getText()));
       model.setMovementSpeed(Integer.parseInt(this.speedMovementsTextBox.getText()));
       model.setReOrganisationSpeed(Integer.parseInt(this.speedOrganizationTextBox.getText()));
       controller.start();
       this.setVisible(false);
    }//GEN-LAST:event_okButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField speedGeneralTextBox;
    private javax.swing.JTextField speedMovementsTextBox;
    private javax.swing.JTextField speedOrganizationTextBox;
    private javax.swing.JCheckBox writeInFileExeCheckBoxNo;
    private javax.swing.JCheckBox writeInFileExeCheckBoxYes;
    // End of variables declaration//GEN-END:variables

}
